= GTFS-Schedule
:doctype: book

Be on time for your next public transport service.

== Motivation

____
What time do I need to leave the office to minimize waiting time for my train?
____

The command is intended to be invoked frequently in a status bar (such as
https://github.com/jaor/xmobar[xmobar]) showing next departing services for one
particular stop.

The command shows remaining minutes in order to leave the current spot
(e.g. office) to minimize the waiting time at the bus or train stop.

== Features

Note that most of these features have never been tested with a wide range of
audience, so take this list with a grain of salt:

* automatically sets up the static data set
* automatically update the static data set to keep an always up-to-date schedule
* real time updates supported (some features are not supported by the actual real time feeds):
** delays
** congestion information
** occupancy status

== Non Goals

* a route planner

== Installation

=== From source

Haskell provides a tool called
https://docs.haskellstack.org/en/stable/README/[stack] which can be installed on
many systems.

Using `stack` you can compile and install:

----
stack install
----

in your local folder (`~/.local`). Make sure it is in your `$PATH`.

=== Packages

Experimental packages are available for Fedora via
https://copr.fedorainfracloud.org/coprs/romanofski/gtfsschedule/[copr].

=== Credits

Without the help this software would have not been possible to build:

* Fraser Tweedale
* #BFPG

include::ChangeLog.adoc[]

== Man Page

:leveloffset: +2

include::man/gtfsschedule.1.adoc[]

:leveloffset: -2
